import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/login",
        "/demo",
        "/dashboard",
        "/workspace",
        "/children",
        "/attendance",
        "/billing",
        "/messages",
        "/incidents",
        "/daily-reports",
        "/guardians",
        "/staff-management",
        "/settings",
        "/enrollment",
        "/rooms",
        "/audit",
        "/policies",
        "/parent",
        "/unauthorized",
        "/api",
        "/offline",
        "/auth",
        "/invite",
        "/surveys",
        "/locations",
        "/analytics",
        "/compliance",
        "/reports",
        "/documents",
        "/calendar",
        "/announcements",
        "/learning-stories",
        "/records",
        "/staff",
        "/enroll",
        "/health-checks",
        "/meal-planning",
        "/curriculum",
        "/update-requests",
      ],
    },
    sitemap: "https://brightcareos.com/sitemap.xml",
  };
}
